package dev.slne.surf.chat.paper.permission

import dev.slne.surf.chat.core.common.permission.ChatPermissions
import dev.slne.surf.surfapi.bukkit.api.permission.PermissionRegistry

object SurfChatPermissionRegistry : PermissionRegistry() {

    val AUTO_CHAT_DISABLING_BYPASS = create(ChatPermissions.AUTO_CHAT_DISABLING_BYPASS)

    val TEAM_BYPASS_FILTER = create(ChatPermissions.TEAM_BYPASS_FILTER)
    val TEAM_BYPASS_SPY = create(ChatPermissions.TEAM_BYPASS_SPY)
    val TEAM_BYPASS_FUNCTIONALITY = create(ChatPermissions.TEAM_BYPASS_FUNCTIONALITY)
    val TEAM_NOTIFY_FUNCTIONALITY = create(ChatPermissions.TEAM_NOTIFY_FUNCTIONALITY)
    val TEAM_NOTIFY_DELETION = create(ChatPermissions.TEAM_NOTIFY_DELETION)

    val COMMAND_SURFCHAT = create(ChatPermissions.COMMAND_SURFCHAT)
    val COMMAND_SURFCHAT_DELETE = create(ChatPermissions.COMMAND_SURFCHAT_DELETE)
    val COMMAND_SURFCHAT_TELEPORT = create(ChatPermissions.COMMAND_SURFCHAT_TELEPORT)

    val COMMAND_SURFCHAT_FUNCTIONALITY = create(ChatPermissions.COMMAND_SURFCHAT_FUNCTIONALITY)
    val COMMAND_SURFCHAT_FUNCTIONALITY_TOGGLE =
        create(ChatPermissions.COMMAND_SURFCHAT_FUNCTIONALITY_TOGGLE)
    val COMMAND_SURFCHAT_FUNCTIONALITY_STATUS =
        create(ChatPermissions.COMMAND_SURFCHAT_FUNCTIONALITY_STATUS)
    val COMMAND_SURFCHAT_FUNCTIONALITY_LIST =
        create(ChatPermissions.COMMAND_SURFCHAT_FUNCTIONALITY_LIST)

    val COMMAND_SURFCHAT_LOOKUP = create(ChatPermissions.COMMAND_SURFCHAT_LOOKUP)
    val COMMAND_SURFCHAT_LOOKUP_HELP = create(ChatPermissions.COMMAND_SURFCHAT_LOOKUP_HELP)

    val COMMAND_SURFCHAT_RELOAD = create(ChatPermissions.COMMAND_SURFCHAT_RELOAD)
    val COMMAND_SURFCHAT_METRICS = create(ChatPermissions.COMMAND_SURFCHAT_METRICS)

    val COMMAND_IGNORE = create(ChatPermissions.COMMAND_IGNORE)
    val COMMAND_IGNORE_LIST = create(ChatPermissions.COMMAND_IGNORE_LIST)

    val COMMAND_DENYLIST = create(ChatPermissions.COMMAND_DENYLIST)
    val COMMAND_DENYLIST_ADD = create(ChatPermissions.COMMAND_DENYLIST_ADD)
    val COMMAND_DENYLIST_REMOVE = create(ChatPermissions.COMMAND_DENYLIST_REMOVE)
    val COMMAND_DENYLIST_LIST = create(ChatPermissions.COMMAND_DENYLIST_LIST)

    val COMMAND_DENYLIST_ACTION = create(ChatPermissions.COMMAND_DENYLIST_ACTION)
    val COMMAND_DENYLIST_ACTION_ADD = create(ChatPermissions.COMMAND_DENYLIST_ACTION_ADD)
    val COMMAND_DENYLIST_ACTION_REMOVE = create(ChatPermissions.COMMAND_DENYLIST_ACTION_REMOVE)
    val COMMAND_DENYLIST_ACTION_LIST = create(ChatPermissions.COMMAND_DENYLIST_ACTION_LIST)
    val COMMAND_DENYLIST_ACTION_CLEAR = create(ChatPermissions.COMMAND_DENYLIST_ACTION_CLEAR)

    val COMMAND_DENYLIST_DEFAULTS = create(ChatPermissions.COMMAND_DENYLIST_DEFAULTS)
    val COMMAND_DENYLIST_CLEAR = create(ChatPermissions.COMMAND_DENYLIST_CLEAR)

    val COMMAND_DIRECT_SPY = create(ChatPermissions.COMMAND_DIRECT_SPY)
    val COMMAND_DIRECT_SPY_CLEAR = create(ChatPermissions.COMMAND_DIRECT_SPY_CLEAR)

    val COMMAND_CHANNEL = create(ChatPermissions.COMMAND_CHANNEL)
    val COMMAND_CHANNEL_ACCEPT = create(ChatPermissions.COMMAND_CHANNEL_ACCEPT)
    val COMMAND_CHANNEL_CREATE = create(ChatPermissions.COMMAND_CHANNEL_CREATE)
    val COMMAND_CHANNEL_DELETE = create(ChatPermissions.COMMAND_CHANNEL_DELETE)
    val COMMAND_CHANNEL_LIST = create(ChatPermissions.COMMAND_CHANNEL_LIST)
    val COMMAND_CHANNEL_INFO = create(ChatPermissions.COMMAND_CHANNEL_INFO)
    val COMMAND_CHANNEL_BAN = create(ChatPermissions.COMMAND_CHANNEL_BAN)
    val COMMAND_CHANNEL_UNBAN = create(ChatPermissions.COMMAND_CHANNEL_UNBAN)
    val COMMAND_CHANNEL_KICK = create(ChatPermissions.COMMAND_CHANNEL_KICK)
    val COMMAND_CHANNEL_JOIN = create(ChatPermissions.COMMAND_CHANNEL_JOIN)
    val COMMAND_CHANNEL_LEAVE = create(ChatPermissions.COMMAND_CHANNEL_LEAVE)
    val COMMAND_CHANNEL_PROMOTE = create(ChatPermissions.COMMAND_CHANNEL_PROMOTE)
    val COMMAND_CHANNEL_DEMOTE = create(ChatPermissions.COMMAND_CHANNEL_DEMOTE)
    val COMMAND_CHANNEL_TRANSFER = create(ChatPermissions.COMMAND_CHANNEL_TRANSFER)
    val COMMAND_CHANNEL_INVITE = create(ChatPermissions.COMMAND_CHANNEL_INVITE)
    val COMMAND_CHANNEL_REVOKE = create(ChatPermissions.COMMAND_CHANNEL_REVOKE)
    val COMMAND_CHANNEL_DECLINE = create(ChatPermissions.COMMAND_CHANNEL_DECLINE)
    val COMMAND_CHANNEL_MEMBERS = create(ChatPermissions.COMMAND_CHANNEL_MEMBERS)

    val COMMAND_CHANNEL_VISIBILITY = create(ChatPermissions.COMMAND_CHANNEL_VISIBILITY)

    val COMMAND_CHANNEL_ADMIN = create(ChatPermissions.COMMAND_CHANNEL_ADMIN)
    val COMMAND_CHANNEL_ADMIN_MOVE = create(ChatPermissions.COMMAND_CHANNEL_ADMIN_MOVE)
    val COMMAND_CHANNEL_ADMIN_JOIN = create(ChatPermissions.COMMAND_CHANNEL_ADMIN_JOIN)
    val COMMAND_CHANNEL_ADMIN_DELETE = create(ChatPermissions.COMMAND_CHANNEL_ADMIN_DELETE)
    val COMMAND_CHANNEL_ADMIN_SPY = create(ChatPermissions.COMMAND_CHANNEL_ADMIN_SPY)
    val COMMAND_CHANNEL_ADMIN_SPY_CLEAR = create(ChatPermissions.COMMAND_CHANNEL_ADMIN_SPY_CLEAR)

    val COMMAND_TEAMCHAT = create(ChatPermissions.COMMAND_TEAMCHAT)
    val COMMAND_TELL = create(ChatPermissions.COMMAND_TELL)
    val COMMAND_REPLY = create(ChatPermissions.COMMAND_REPLY)

    val COMMAND_SURFCHAT_AI_MODERATION = create(ChatPermissions.COMMAND_SURFCHAT_AI_MODERATION)
}
