name: Publish to Maven & Create GitHub Release

on:
  push:
    branches:
      - version/*
      - feat/signed-message-sending-pai
  workflow_dispatch:

jobs:
  build:
    uses: SLNE-Development/surf-workflows/.github/workflows/build-publish-release-gradle.yml@master
    with:
      modules: "surf-chat-paper-*-all.jar;surf-chat-microservice-*-all.jar"
    secrets: inherit
